mixed-port: 2017
allow-lan: true
mode: Rule
log-level: silent
proxies:
- name: outNode
  type: socks5
  server: us.ipdodo.cloud
  port: 10800
  username: yds_default_448-dh-2-region-us-session-89374315-30
  password: 655FA9B1551AF0EA
  skip-cert-verify: true
- name: turboNode
  type: vmess
  server: c713s3.portablesubmarines.com
  port: 10097
  uuid: f43d7e83-37f9-4cb1-ac12-a4b0512f05a1
  alterId: 0
  cipher: auto
proxy-groups:
- name: relay
  type: relay
  proxies:
  - turboNode
  - outNode
rules:
- GEOIP,LAN, DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-KEYWORD,static,turboNode
- DOMAIN-KEYWORD,cdn,turboNode
- DOMAIN-KEYWORD,ibytedtos,turboNode
- DOMAIN-KEYWORD,gvt1,turboNode
- DOMAIN-KEYWORD,pitaya-clientai,turboNode
- DOMAIN-KEYWORD,effect,turboNode
- DOMAIN-KEYWORD,aliyuncs,DIRECT
- MATCH,relay
